exclude:
- 3pole_lowpass/3pole_lowpass.md
- README.md
- _dump/fourier_transform_fractional_derivative.md
- _dump/fractional_calculus_temp.md
- _dump/fractional_zener_temp.md
- _dump/highpass.md
- _dump/impliciteuler.md
- _dump/implicitwaveequation_temp.md
- _dump/ndboct_temp.md
- _dump/reverb.md
- _dump/sigma_approximation.md
- _dump/time_integration.md
- _dump/time_integration_temp.md
- _dump/waveequation2d_temp.md
- _dump/waveequation_misc.md
- _dump/waveequation_temp.md
- _dump/waveequationgibbs_temp.md
- _stab/choir.md
- _stab/energy_decay_curve.md
- _stab/nonliner_acoustics.md
- _stab/waveequation_parameters.md
- _stab/wavefunction.md
- am_pitchshift/am_pitchshift.md
- basic_fir/basic_fir.md
- burgers_exact/burgers_exact.md
- burgers_exact/demo/README.md
- burgers_godunov/burgers_godunov.md
- control_rate_interpolation/control_rate_interpolation.md
- delay/_dump/fractionaldelayfilter.md
- delay/delay.md
- doublefilter/doublefilter.md
- dr110_cymbal/demo/README.md
- dr110_cymbal/dr110_cymbal.md
- exponential_envelope/exponential_envelope.md
- exppoly_envelope/_dump/expadenvelope.md
- exppoly_envelope/exppoly_envelope.md
- fractional_delay_filter_socp/fractional_delay_filter_socp.md
- gibbs/gibbs.md
- golly_generations_clustering/demo/README.md
- golly_generations_clustering/gallery.md
- golly_generations_clustering/golly_generations_clustering.md
- grunwald_letnikov/demo/README.md
- grunwald_letnikov/grunwald_letnikov.md
- heat_wave_equation/demo/README.md
- heat_wave_equation/heat_wave_equation.md
- linear_envelope/linear_envelope.md
- multipitch_analysis/eac.md
- ndboct/ndboct.md
- one_sec_sounds_clustering/one_sec_sounds_clustering.md
- parabolic_envelope/_dump/note.md
- parabolic_envelope/parabolic_envelope.md
- parabolic_envelope/parabolic_envelope_exp.md
- pitch_estimation/pitch_estimation.md
- pitch_estimation/plot_gallery_pitch_estimation.md
- polyblamp_residual/polyblamp_residual.md
- ptr_oscillator/_dump/LKslope.md
- ptr_oscillator/_dump/exp_ptr.md
- ptr_oscillator/_dump/ptr.mac.md
- ptr_oscillator/_dump/ptr_equation.md
- ptr_oscillator/_dump/tri_equation.md
- ptr_oscillator/ptr_maxima.md
- ptr_oscillator/ptr_oscillator.md
- ptr_trapezoid/_dump/naive.md
- ptr_trapezoid/ptr_trapezoid.md
- waveequation/waveequation.md
- waveequation2d/waveequation2d.md
- waveequation_fractional_zener/demo/README.md
- waveequation_fractional_zener/waveequation_fractional_zener.md
- waveequation_newmark_beta/waveequation_newmark_beta.md
- waveequationimplicit/demo/README.md
- waveequationimplicit/waveequationimplicit.md
- wavetable/_dump/note.md
- wavetable/_dump/snippet.md
- wavetable/wavetable.md
