exclude:
- README.md
- _dump/fourier_transform_fractional_derivative.md
- _dump/fractional_calculus_temp.md
- _dump/fractional_zener_temp.md
- _dump/highpass.md
- _dump/impliciteuler.md
- _dump/implicitwaveequation_temp.md
- _dump/ndboct_temp.md
- _dump/reverb.md
- _dump/sigma_approximation.md
- _dump/time_integration.md
- _dump/time_integration_temp.md
- _dump/waveequation2d_temp.md
- _dump/waveequation_misc.md
- _dump/waveequation_temp.md
- _dump/waveequationgibbs_temp.md
- _stab/choir.md
- _stab/energy_decay_curve.md
- _stab/nonliner_acoustics.md
- _stab/waveequation_parameters.md
- _stab/wavefunction.md
- am_pitchshift/am_pitchshift.md
- basic_fir/basic_fir.md
- burgers_exact/burgers_exact.md
- burgers_exact/demo/README.md
- burgers_godunov/burgers_godunov.md
- delay/_dump/fractionaldelayfilter.md
- delay/delay.md
- dr110_cymbal/demo/README.md
- dr110_cymbal/dr110_cymbal.md
- fractional_delay_filter_socp/fractional_delay_filter_socp.md
- gibbs/gibbs.md
- golly_generations_clustering/demo/README.md
- golly_generations_clustering/gallery.md
- golly_generations_clustering/golly_generations_clustering.md
- grunwald_letnikov/demo/README.md
- grunwald_letnikov/grunwald_letnikov.md
- heat_wave_equation/demo/README.md
- heat_wave_equation/heat_wave_equation.md
- multipitch_analysis/eac.md
- ndboct/ndboct.md
- one_sec_sounds_clustering/one_sec_sounds_clustering.md
- pitch_estimation/pitch_estimation.md
- pitch_estimation/plot_gallery_pitch_estimation.md
- waveequation/waveequation.md
- waveequation2d/waveequation2d.md
- waveequation_fractional_zener/demo/README.md
- waveequation_fractional_zener/waveequation_fractional_zener.md
- waveequation_newmark_beta/waveequation_newmark_beta.md
- waveequationimplicit/demo/README.md
- waveequationimplicit/waveequationimplicit.md
- wavetable/_dump/note.md
- wavetable/_dump/snippet.md
- wavetable/wavetable.md
