exclude:
- 3pole_lowpass\3pole_lowpass.md
- README.md
- _stab\choir.md
- _stab\energy_decay_curve.md
- _stab\nonliner_acoustics.md
- _stab\waveequation_parameters.md
- _stab\wavefunction.md
- am_pitchshift\am_pitchshift.md
- basic_fir\basic_fir.md
- burgers_exact\burgers_exact.md
- burgers_exact\demo\README.md
- burgers_godunov\burgers_godunov.md
- control_rate_interpolation\control_rate_interpolation.md
- delay\delay.md
- doublefilter\doublefilter.md
- dr110_cymbal\demo\README.md
- dr110_cymbal\dr110_cymbal.md
- exponential_envelope\exponential_envelope.md
- exppoly_envelope\exppoly_envelope.md
- fractional_delay_filter_socp\fractional_delay_filter_socp.md
- gibbs\gibbs.md
- golly_generations_clustering\demo\README.md
- golly_generations_clustering\gallery.md
- golly_generations_clustering\golly_generations_clustering.md
- grunwald_letnikov\demo\README.md
- grunwald_letnikov\grunwald_letnikov.md
- heat_wave_equation\demo\README.md
- heat_wave_equation\heat_wave_equation.md
- linear_envelope\linear_envelope.md
- ndboct\ndboct.md
- one_sec_sounds_clustering\one_sec_sounds_clustering.md
- parabolic_envelope\parabolic_envelope.md
- parabolic_envelope\parabolic_envelope_exp.md
- pitch_estimation\pitch_estimation.md
- pitch_estimation\plot_gallery_pitch_estimation.md
- polyblamp_residual\polyblamp_residual.md
- polyblep_residual\polyblep_residual.md
- ptr_oscillator\ptr_maxima.md
- ptr_oscillator\ptr_oscillator.md
- ptr_trapezoid\ptr_trapezoid.md
- s_curve_step_response_filter\s_curve_step_response_filter.md
- waveequation2d\waveequation2d.md
- waveequation\waveequation.md
- waveequation_fractional_zener\demo\README.md
- waveequation_fractional_zener\waveequation_fractional_zener.md
- waveequation_newmark_beta\waveequation_newmark_beta.md
- waveequationimplicit\demo\README.md
- waveequationimplicit\waveequationimplicit.md
- wavetable\wavetable.md
